language: node_js
node_js:
- '12'
before_script: npm test
script: npm run docs
deploy:
  name: Dave Bot
  local-dir: docs
  project-name: vanillas
  email: arizonatribe@gmail
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
